apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-applications
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - service: sealed-secrets
            repoUrl: "https://bitnami-labs.github.io/sealed-secrets"
            chartVersion: "2.17.9"
            namespace: kube-system
          - service: immich
            repoUrl: "https://immich-app.github.io/immich-charts"
            chartVersion: "0.10.1"
            url: "https://immich.tomas-homelab.com"
            namespace: immich
            kustomize: true
          - service: cnpg
            repoUrl: "https://cloudnative-pg.github.io/charts"
            chartVersion: "0.26.0"
            namespace: cnpg-system
  template:
    metadata:
      name: "{{.service}}"
    spec:
      destination:
        name: applications
        namespace: "{{.namespace}}"
      project: "default"
      revisionHistoryLimit: 4
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    metadata:
      annotations:
        {{- if .url }}
        link.argocd.argoproj.io/external-link: "{{.url}}"
        {{- end }}
    spec:
      sources:
        - repoURL: '{{.repoUrl}}'
          targetRevision: '{{.chartVersion}}'
          chart: '{{.service}}'
          helm:
            releaseName: '{{.service}}'
            valueFiles:
              - $values/apps/{{.service}}/values.yaml
        - repoURL: 'https://github.com/my-org/tomas-homelab.git'
          targetRevision: main
          ref: values